title: Huanfa Chen
description: Geographical Information Science, Spatio-temporal Data Mining, Spatial Optimisation
theme: jekyll-theme-cayman
comments: true
disqus: huanfachen
google_analytics: UA-96998681-1
